<?= $this->doctype() ?>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>AdminLTE 2 | Dashboard</title>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
                ->prependStylesheet($this->basePath('bower_components/bootstrap-daterangepicker/daterangepicker.css'))
                ->prependStylesheet($this->basePath('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'))
                ->prependStylesheet($this->basePath('bower_components/jvectormap/jquery-jvectormap.css'))
                ->prependStylesheet($this->basePath('bower_components/morris.js/morris.css'))
                ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
                ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
                ->prependStylesheet($this->basePath('bower_components/Ionicons/css/ionicons.min.css'))
                ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </head>
    
    <body class="hold-transition register-page">
        <div class="register-box tiramargin">
            <?= $this->content ?>
        </div>
        <!-- /.register-box -->

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->prependFile($this->basePath('dist/js/demo.js'))
                ->prependFile($this->basePath('dist/js/pages/dashboard.js'))
                ->prependFile($this->basePath('dist/js/adminlte.min.js'))
                ->prependFile($this->basePath('bower_components/fastclick/lib/fastclick.js'))
                ->prependFile($this->basePath('bower_components/jquery-slimscroll/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
                ->prependFile($this->basePath('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js'))
                ->prependFile($this->basePath('bower_components/bootstrap-daterangepicker/daterangepicker.js'))
                ->prependFile($this->basePath('bower_components/moment/min/moment.min.js'))
                ->prependFile($this->basePath('bower_components/jquery-knob/dist/jquery.knob.min.js'))
                ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
                ->prependFile($this->basePath('plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
                ->prependFile($this->basePath('bower_components/jquery-sparkline/dist/jquery.sparkline.min.js'))
                ->prependFile($this->basePath('bower_components/morris.js/morris.min.js'))
                ->prependFile($this->basePath('bower_components/raphael/raphael.min.js'))
                ->prependFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('bower_components/jquery-ui/jquery-ui.min.js'))
                ->prependFile($this->basePath('bower_components/jquery/dist/jquery.min.js'))
        ?>


        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
        
        <?= $this->inlineScript() ?>

    </body>
</html>
