
<div class="register-logo">
    <a href="../../index2.html"><b>Admin</b>LTE</a>
</div>

<div class="register-box-body">
    <p class="login-box-msg">Digite sua nova senha</p>

    <form action="../../index.html" method="post">
        
        <div class="form-group has-feedback">
            <input type="email" class="form-control" placeholder="Email">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Nova Senha</button>
            </div>
            <!-- /.col -->
        </div>
    </form>
    
    <div class="row">
        <div class="col-xs-6">
            <a href="#" class="text-center">Votar para login</a>            
        </div>            
    </div>
    
</div>
<!-- /.form-box -->