<section class="content-header">
    <h1>
        Dashboard
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Meus Tickets</h3>

                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <tr>
                            <th>#</th>
                            <th>Prioridade</th>
                            <th>Data</th>
                            <th>Ação</th>
                            <th>Opição</th>
                        </tr>
                        <tr>
                            <td>1</td>
                            <td>Update Software</td>
                            <td><span class="label label-success">Em andamento</span></td>
                            <td>12/12/2019</td>
                            <td>
                                <button type="button" class="btn btn-warning"><i class="fa fa-edit"></i>Editar</button>
                                <button type="button" class="btn btn-danger"><i class="fa fa-trash"></i>Excluir</button>
                            </td>
                        </tr>

                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

</section>
<!-- /.content -->
